// <auto-generated />
using System;
using ActiveSync.Core.State;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActiveSync.Core.Migrations.Sqlite
{
    [DbContext(typeof(SqliteSyncDbContext))]
    partial class SqliteSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ActiveSync.Core.State.AccountEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AccountEntries");
                });

            modelBuilder.Entity("ActiveSync.Core.State.AccountsStamp", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountsStamps");
                });

            modelBuilder.Entity("ActiveSync.Core.State.CollectionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilterType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastClientAddsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastClientChangesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceKey", "CollectionId")
                        .IsUnique();

                    b.ToTable("CollectionStates");
                });

            modelBuilder.Entity("ActiveSync.Core.State.DavItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserFolderKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserFolderKey", "Href")
                        .IsUnique();

                    b.ToTable("DavItems");
                });

            modelBuilder.Entity("ActiveSync.Core.State.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceInfoJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderSyncKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastProtocolVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncRequestJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PendingAccountWipe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PingParamsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyDocHash")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PolicyKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoveryPasswordProtected")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName", "DeviceId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ActiveSync.Core.State.DeviceFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceKey", "ServerId")
                        .IsUnique();

                    b.ToTable("DeviceFolders");
                });

            modelBuilder.Entity("ActiveSync.Core.State.GlobalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("ActiveSync.Core.State.LocalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ItemDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserName", "Collection");

                    b.ToTable("LocalItems");
                });

            modelBuilder.Entity("ActiveSync.Core.State.LoginBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName", "DeviceId")
                        .IsUnique();

                    b.ToTable("LoginBlocks");
                });

            modelBuilder.Entity("ActiveSync.Core.State.OofSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousActiveScript")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("OofSettings");
                });

            modelBuilder.Entity("ActiveSync.Core.State.ServerCertificate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PfxProtected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerCertificates");
                });

            modelBuilder.Entity("ActiveSync.Core.State.SettingsStamp", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingsStamps");
                });

            modelBuilder.Entity("ActiveSync.Core.State.SharedCalendarGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionHref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName", "CollectionHref")
                        .IsUnique();

                    b.ToTable("SharedCalendarGrants");
                });

            modelBuilder.Entity("ActiveSync.Core.State.UserFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackendKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EasClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentBackendKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName", "BackendKey")
                        .IsUnique();

                    b.ToTable("UserFolders");
                });

            modelBuilder.Entity("ActiveSync.Core.State.CollectionState", b =>
                {
                    b.HasOne("ActiveSync.Core.State.Device", "Device")
                        .WithMany("Collections")
                        .HasForeignKey("DeviceKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ActiveSync.Core.State.DavItem", b =>
                {
                    b.HasOne("ActiveSync.Core.State.UserFolder", "Folder")
                        .WithMany("DavItems")
                        .HasForeignKey("UserFolderKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ActiveSync.Core.State.DeviceFolder", b =>
                {
                    b.HasOne("ActiveSync.Core.State.Device", "Device")
                        .WithMany("Folders")
                        .HasForeignKey("DeviceKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ActiveSync.Core.State.Device", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Folders");
                });

            modelBuilder.Entity("ActiveSync.Core.State.UserFolder", b =>
                {
                    b.Navigation("DavItems");
                });
#pragma warning restore 612, 618
        }
    }
}
